### PR TITLE
relocated services from elbrus core project

### PR DESCRIPTION
**Pull request by ArseniVorhan**

### CODE REVIEW

**Comment by ArseniVorhan** [comment]
@stievena I added some services that we need to use your bundle

**Comment by ArseniVorhan** [comment]
@stievena done

**Comment by stievena** [comment]
@ArseniVorhan Can you please refactor the method getProductsContent, this is redundant with the method getProducts. If you need a method with no sorting then it should be implemented this way:
`
public <T> ContentSet<T> getProducts(String familyId, String context, int pageSize, int startFrom, List<Segment[]> segments, Class modelClass) {
        return getProducts(familyId,context,pageSize,startFrom,segments,null,true,modelClass);
    }
`

**Comment by stievena** [comment]
@ArseniVorhan   Please factor the code for getStoreContent also

**Comment by ArseniVorhan** [comment]
@stievena I removed methods getStores and getProducts
also I add sorting for getProductsContent method

**Pull request closed without merging**
